# Generated by Django 5.2.6 on 2025-12-06 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_functionality', models.CharField(choices=[('F1', 'Sécurisation des prompts'), ('F2', 'Analyse de code')], default='F2', help_text='F1 = sécurisation des prompts, F2 = analyse de code', max_length=2)),
                ('original_text', models.TextField(blank=True, help_text="Texte original fourni par l'utilisateur", null=True)),
                ('secured_text', models.TextField(blank=True, help_text="Texte sécurisé et amélioré par l'IA", null=True)),
                ('risk_level', models.CharField(blank=True, help_text='Niveau de risque détecté', max_length=50, null=True)),
                ('input_text', models.TextField(blank=True, help_text="Code et/ou prompt fourni par l'utilisateur", null=True)),
                ('output_text', models.TextField(blank=True, help_text="Résultat généré par l'IA", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
