# Generated by Django 5.2.6 on 2025-12-06 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type_functionality',
            field=models.CharField(choices=[('F1', 'Sécurisation des prompts'), ('F2', 'Analyse de code')], default='F1', help_text='F1 = sécurisation des prompts, F2 = analyse de code', max_length=2),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL),
        ),
    ]
