# Generated by Django 5.2.8 on 2025-12-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type_functionality',
            field=models.CharField(choices=[('F1', 'Sécurisation des prompts'), ('F2', 'Analyse de code')], default='F1', help_text='F1 = sécurisation des prompts, F2 = analyse de code', max_length=2),
        ),
    ]
