# Generated by Django 5.2.6 on 2025-12-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_alter_prompt_type_functionality'),
        ('prompt', '0002_alter_prompt_type_functionality_alter_prompt_user'),
    ]

    operations = [
    ]
