# Generated by Django 5.2.8 on 2025-12-06 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompt', '0002_alter_prompt_type_functionality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('language', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='note_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CodeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_analysis', to='prompt.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcms', to='code_analysis.note')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='code_analysis.qcm')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes_explained', models.TextField()),
                ('best_practices', models.TextField(blank=True)),
                ('errors_corrected', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='code_analysis.codeanalysis')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='resultat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='code_analysis.resultat'),
        ),
        migrations.CreateModel(
            name='ResultatQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='code_analysis.qcm')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_analysis.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_qcm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
